package com.rtj;

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;

/**
 * Employee generated by hbm2java
 */
@Entity
public class Employee implements Serializable {
	

	private int eid;
	private String ename;

	public Employee() {
	}

	public Employee(int eid) {
		this.eid = eid;
	}

	public Employee(int eid, String ename) {
		this.eid = eid;
		this.ename = ename;
	}
	@Id
	@GeneratedValue(strategy =GenerationType.AUTO)
	@Column(name = "eid", unique = true, nullable = false)

	public int getEid() {
		return this.eid;
	}

	public void setEid(int eid) {
		this.eid = eid;
	}

	public String getEname() {
		return this.ename;
	}

	public void setEname(String ename) {
		this.ename = ename;
	}

}
